### ISSUE TITLE
pretext code

### ISSUE THREAD

**Issue by cir7** [FingerRec/BE#4]
hi jinpeng:
it seems that there is no code for pretext training(src/Pretext), do you have plan to release related code?

**Comment by FingerRec** [comment]
Hi cir7,

Thanks for your interest in our work and sorry for late reply. As we integrate our BE into several well-known pretext baselines  and not modify these public available code a lot,  we may not include in this codebase because some of them not release the copyright clarify.

Yours,
Awiny
