### ISSUE TITLE
About the I3D backbone 

### ISSUE THREAD

**Issue by Mark12Ding** [FingerRec/BE#7]
Hi all,
I am quite interested about your work. When I dive into the code, I am questioned about the setting (https://github.com/FingerRec/BE/blob/632c3aa0eaa3acc24a545ec05a9a36f96592cb2c/src/Contrastive/model/i3d.py#L293) in i3d.py. The kernel here is set as (7,1,1), but the dimension of pretrained feature is already B * C * 1 * 1 * 1. What's the purpose here? Looking forward to your reply.

Best.

**Comment by FingerRec** [comment]
In original implement, they use 64 frames. This kernel is not helpful in pertaining. But it leads to better performance when fine-tuning on small dataset.
