### ISSUE TITLE
Where can i find package "bk" ?

### ISSUE THREAD

**Issue by idealwei** [FingerRec/BE#8]
I try to run "scripts/ucf101/pt_and_tf.sh", but i got the following error message. 

[Error Messeage]: 
" from bk.inpainting_src.spatial_inpainting import PatchDis, PatchPaint
ModuleNotFoundError: No module named 'bk.inpainting_src'
"
 I couldn't find the "bk" package in your code.  Can you help me figure out this problem ?

**Comment by FingerRec** [comment]
its a no-use package, just comment it
